---
apiVersion: v1
kind: Service
metadata:
  name: carts
  labels:
    name: carts
    namespace: default
    app: carts
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 80
#    name: http
    name: tcp
  selector:
    name: carts
