---
apiVersion: v1
kind: Service
metadata:
  name: queue-master
  labels:
    name: queue-master
    app: queue-master
  annotations:
    prometheus.io/path: "/prometheus"
  namespace: default
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 80
    name: http
  selector:
    name: queue-master
