---
apiVersion: v1
kind: Service
metadata:
  name: user-db
  labels:
    name: user-db
    app: user-db
  namespace: default
spec:
  ports:
    # the port that this service should serve on
  - port: 27017
    targetPort: 27017
    name: mongo
  selector:
    name: user-db

