---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
  labels:
    name: catalogue
    app: catalogue
  namespace: default
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 80
#    name: http
    name: tcp
  selector:
    name: catalogue
