---
apiVersion: v1
kind: Service
metadata:
  name: front-end
  labels:
    name: front-end
    app: front-end
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port: 80
#    name: http
    name: tcp
    targetPort: 8079
    nodePort: 32001
  selector:
    name: front-end
