---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    name: rabbitmq
    app: rabbitmq
    namespace: default
spec:
  ports:
    # the port that this service should serve on
  - port: 5672
    name: tcp-rabbitmq
    targetPort: 5672
  - port: 9090
    name: exporter
    targetPort: exporter
    protocol: TCP
  selector:
    name: rabbitmq
